### PR TITLE
Add `pyproject.toml` according to `PEP 517`

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by encukou** [comment]
Thank you!
PEP 517 also says:

> If the pyproject.toml file is absent, or the build-backend key is missing, the source tree is not using this specification, and tools should revert to the legacy behaviour of running setup.py (either directly, or by implicitly invoking the `setuptools.build_meta:__legacy__` backend).

So the change is cosmetic. And we can't really use a different backend than setuptools since the project needs to be compatible with ancient versions of stuff.
I'll not treat this as a priority, but I'll merge & include it in a release when some user-visible change comes along.

**Comment by KOLANICH** [comment]
>So the change is cosmetic

Not so cosmetic. Some tools' authors may want to rely on presence of that file rather than to probe different files.

**Comment by encukou** [comment]
> Not so cosmetic. Some tools' authors may want to rely on presence of that file rather than to probe different files.

OK, that makes sense. 
Can you share the which tool you're concerned about, if there's a specific one? It would be nice to know more about the audience :)

**Comment by KOLANICH** [comment]
Thanks for the interest. https://github.com/ipi-py/ipi.py . But it is WiP currently.

**Pull request merged**
