### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by encukou** [comment]
Thanks, this looks reasonable. I didn't occur to me to release a header-only library on PyPI.
Thank you for adding me to the PyPI maintainers as well!

I see that setuptools flattens the directory of headers. Instead of:

```
include/
├── py3c
│   ├── capsulethunk.h
│   ├── comparison.h
│   ├── compat.h
│   ├── fileshim.h
│   ├── py3shims.h
│   └── tpflags.h
└── py3c.h
```
there is:
```
__venv__/include/site/python3.6/
└── py3c
    ├── capsulethunk.h
    ├── comparison.h
    ├── compat.h
    ├── fileshim.h
    ├── py3c.h
    ├── py3shims.h
    └── tpflags.h
```

Wouldn't this be a problem?

**Comment by xoviat** [comment]
If you add the include directory as the root, and include `py3c/py3c.h`, it should work.

**Comment by encukou** [comment]
I've addressed several nitpicks in https://github.com/xoviat/py3c/pull/1. Do those look reasonable to you?

**Comment by xoviat** [comment]
Have you used `setuptools_scm`?

**Comment by encukou** [comment]
Merged in 59cd917. I'll upload to PyPI as well.
Thanks!

**Comment by encukou** [comment]
Hi @xoviat,
Recently you somehow disappeared from GitHub, and I couldn't find a contact e-mail for you in the Git logs. I see you're back now; welcome!
I've removed you from the “Owner” list on PyPI. If you want I can add you back, but in that case could you please send me an e-mail so I have a better way to reach you?
Or I'm also happy to maintain py3c alone.

**Pull request closed without merging**
